# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_front', models.ImageField(upload_to=b'')),
                ('id_back', models.ImageField(upload_to=b'')),
                ('id_number', models.CharField(max_length=18)),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=6)),
                ('verification_code', models.CharField(max_length=4)),
            ],
        ),
    ]
