# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_quantity', models.FloatField(max_length=1000000000)),
                ('task_date', models.DateField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='order_list',
            new_name='orders',
        ),
        migrations.RenameModel(
            old_name='task_list',
            new_name='tasks_available',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='quantity',
            new_name='order_quantity',
        ),
        migrations.RenameField(
            model_name='submitted_tasks',
            old_name='quantity',
            new_name='order_quantity',
        ),
        migrations.RenameField(
            model_name='task_factor',
            old_name='task_valid_date',
            new_name='task_setting_month',
        ),
        migrations.RenameField(
            model_name='tasks_available',
            old_name='fund_valid_date',
            new_name='fund_valid_month',
        ),
        migrations.AlterField(
            model_name='submitted_tasks',
            name='confirmation_status',
            field=models.BooleanField(default=False),
        ),
    ]
