# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_auto_20160523_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitted_tasks',
            name='fund_id',
            field=models.CharField(default=160125, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitted_tasks',
            name='order_date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='submitted_tasks',
            name='register_date',
            field=models.DateField(max_length=10),
        ),
    ]
